package models

type Transaction struct {
	ID      string `json:"id"`
	Type    string `json:"type"`
	Status  string `json:"status"`
	Token   string `json:"token"`
	Amount  string `json:"amount"`
	Value   string `json:"value"`
	Address string `json:"address"`
	Date    string `json:"date"`
	Time    string `json:"time"`
	Fee     string `json:"fee"`
	Hash    string `json:"hash"`
}

type BlockchainDecimal string

const (
	Bitcoin          BlockchainDecimal = "0"
	Ethereum         BlockchainDecimal = "1"
	Vechain          BlockchainDecimal = "2"
	Tron             BlockchainDecimal = "3"
	Icon             BlockchainDecimal = "4"
	Binance          BlockchainDecimal = "5"
	Ripple           BlockchainDecimal = "6"
	Tezos            BlockchainDecimal = "7"
	Nimiq            BlockchainDecimal = "8"
	Stellar          BlockchainDecimal = "9"
	Aion             BlockchainDecimal = "10"
	Cosmos           BlockchainDecimal = "11"
	Theta            BlockchainDecimal = "12"
	Ontology         BlockchainDecimal = "13"
	Zilliqa          BlockchainDecimal = "14"
	IoTeX            BlockchainDecimal = "15"
	Eos              BlockchainDecimal = "16"
	Nano             BlockchainDecimal = "17"
	Nuls             BlockchainDecimal = "18"
	Waves            BlockchainDecimal = "19"
	Aeternity        BlockchainDecimal = "20"
	Nebulas          BlockchainDecimal = "21"
	Fio              BlockchainDecimal = "22"
	Solana           BlockchainDecimal = "23"
	Harmony          BlockchainDecimal = "24"
	Near             BlockchainDecimal = "25"
	Algorand         BlockchainDecimal = "26"
	Iost             BlockchainDecimal = "27"
	Polkadot         BlockchainDecimal = "28"
	Cardano          BlockchainDecimal = "29"
	Neo              BlockchainDecimal = "30"
	Filecoin         BlockchainDecimal = "31"
	MultiversX       BlockchainDecimal = "32"
	OasisNetwork     BlockchainDecimal = "33"
	Decred           BlockchainDecimal = "34"
	Zcash            BlockchainDecimal = "35"
	Groestlcoin      BlockchainDecimal = "36"
	Thorchain        BlockchainDecimal = "37"
	Ronin            BlockchainDecimal = "38"
	Kusama           BlockchainDecimal = "39"
	Zen              BlockchainDecimal = "40"
	BitcoinDiamond   BlockchainDecimal = "41"
	Verge            BlockchainDecimal = "42"
	Nervos           BlockchainDecimal = "43"
	Everscale        BlockchainDecimal = "44"
	Aptos            BlockchainDecimal = "45"
	Nebl             BlockchainDecimal = "46"
	Hedera           BlockchainDecimal = "47"
	TheOpenNetwork   BlockchainDecimal = "48"
	Sui              BlockchainDecimal = "49"
	Greenfield       BlockchainDecimal = "50"
	InternetComputer BlockchainDecimal = "51"
	NativeEvmos      BlockchainDecimal = "52"
	NativeInjective  BlockchainDecimal = "53"
	BitcoinCash      BlockchainDecimal = "54"
	Pactus           BlockchainDecimal = "55"
	Komodo           BlockchainDecimal = "56"
	Polymesh         BlockchainDecimal = "57"
	Sepolia          BlockchainDecimal = "58"
)

//
//type CoinType string
//
//const (
//	Aeternity            CoinType = "0"
//	Aion                 CoinType = "1"
//	Binance              CoinType = "2"
//	Bitcoin              CoinType = "3"
//	BitcoinCash          CoinType = "4"
//	BitcoinGold          CoinType = "5"
//	Callisto             CoinType = "6"
//	Cardano              CoinType = "7"
//	Cosmos               CoinType = "8"
//	Pivx                 CoinType = "9"
//	Dash                 CoinType = "10"
//	Decred               CoinType = "11"
//	DigiByte             CoinType = "12"
//	Dogecoin             CoinType = "13"
//	Eos                  CoinType = "14"
//	Wax                  CoinType = "15"
//	Ethereum             CoinType = "16"
//	EthereumClassic      CoinType = "17"
//	Fio                  CoinType = "18"
//	GoChain              CoinType = "19"
//	Groestlcoin          CoinType = "20"
//	Icon                 CoinType = "21"
//	IoTeX                CoinType = "22"
//	Kava                 CoinType = "23"
//	Kin                  CoinType = "24"
//	Litecoin             CoinType = "25"
//	Monacoin             CoinType = "26"
//	Nebulas              CoinType = "27"
//	Nuls                 CoinType = "28"
//	Nano                 CoinType = "29"
//	Near                 CoinType = "30"
//	Nimiq                CoinType = "31"
//	Ontology             CoinType = "32"
//	Poanetwork           CoinType = "33"
//	Qtum                 CoinType = "34"
//	Xrp                  CoinType = "35"
//	Solana               CoinType = "36"
//	Stellar              CoinType = "37"
//	Tezos                CoinType = "38"
//	Theta                CoinType = "39"
//	ThunderCore          CoinType = "40"
//	Neo                  CoinType = "41"
//	Viction              CoinType = "42"
//	Tron                 CoinType = "43"
//	VeChain              CoinType = "44"
//	Viacoin              CoinType = "45"
//	Wanchain             CoinType = "46"
//	Zcash                CoinType = "47"
//	Firo                 CoinType = "48"
//	Zilliqa              CoinType = "49"
//	Zelcash              CoinType = "50"
//	Ravencoin            CoinType = "51"
//	Waves                CoinType = "52"
//	Terra                CoinType = "53"
//	TerraV2              CoinType = "54"
//	Harmony              CoinType = "55"
//	Algorand             CoinType = "56"
//	Kusama               CoinType = "57"
//	Polkadot             CoinType = "58"
//	Filecoin             CoinType = "59"
//	MultiversX           CoinType = "60"
//	BandChain            CoinType = "61"
//	SmartChainLegacy     CoinType = "62"
//	SmartChain           CoinType = "63"
//	TBinance             CoinType = "64"
//	Oasis                CoinType = "65"
//	Polygon              CoinType = "66"
//	Thorchain            CoinType = "67"
//	Bluzelle             CoinType = "68"
//	Optimism             CoinType = "69"
//	Zksync               CoinType = "70"
//	Arbitrum             CoinType = "71"
//	Ecochain             CoinType = "72"
//	AvalancheCChain      CoinType = "73"
//	Xdai                 CoinType = "74"
//	Fantom               CoinType = "75"
//	CryptoOrg            CoinType = "76"
//	Celo                 CoinType = "77"
//	Ronin                CoinType = "78"
//	Osmosis              CoinType = "79"
//	Ecash                CoinType = "80"
//	Iost                 CoinType = "81"
//	CronosChain          CoinType = "82"
//	SmartBitcoinCash     CoinType = "83"
//	KuCoinCommunityChain CoinType = "84"
//	BitcoinDiamond       CoinType = "85"
//	Boba                 CoinType = "86"
//	Syscoin              CoinType = "87"
//	Verge                CoinType = "88"
//	Zen                  CoinType = "89"
//	Metis                CoinType = "90"
//	Aurora               CoinType = "91"
//	Evmos                CoinType = "92"
//	NativeEvmos          CoinType = "93"
//	Moonriver            CoinType = "94"
//	Moonbeam             CoinType = "95"
//	KavaEvm              CoinType = "96"
//	Kaia                 CoinType = "97"
//	Meter                CoinType = "98"
//	Okxchain             CoinType = "99"
//	Stratis              CoinType = "100"
//	Komodo               CoinType = "101"
//	Nervos               CoinType = "102"
//	Everscale            CoinType = "103"
//	Aptos                CoinType = "104"
//	Nebl                 CoinType = "105"
//	Hedera               CoinType = "106"
//	Secret               CoinType = "107"
//	NativeInjective      CoinType = "108"
//	Agoric               CoinType = "109"
//	Ton                  CoinType = "110"
//	Sui                  CoinType = "111"
//	Stargaze             CoinType = "112"
//	PolygonzkEVM         CoinType = "113"
//	Juno                 CoinType = "114"
//	Stride               CoinType = "115"
//	Axelar               CoinType = "116"
//	Crescent             CoinType = "117"
//	Kujira               CoinType = "118"
//	IoTeXEVM             CoinType = "119"
//	NativeCanto          CoinType = "120"
//	Comdex               CoinType = "121"
//	Neutron              CoinType = "122"
//	Sommelier            CoinType = "123"
//	FetchAI              CoinType = "124"
//	Mars                 CoinType = "125"
//	Umee                 CoinType = "126"
//	Coreum               CoinType = "127"
//	Quasar               CoinType = "128"
//	Persistence          CoinType = "129"
//	Akash                CoinType = "130"
//	Noble                CoinType = "131"
//	Scroll               CoinType = "132"
//	Rootstock            CoinType = "133"
//	ThetaFuel            CoinType = "134"
//	ConfluxeSpace        CoinType = "135"
//	Acala                CoinType = "136"
//	AcalaEVM             CoinType = "137"
//	OpBNB                CoinType = "138"
//	Neon                 CoinType = "139"
//	Base                 CoinType = "140"
//	Sei                  CoinType = "141"
//	ArbitrumNova         CoinType = "142"
//	Linea                CoinType = "143"
//	Greenfield           CoinType = "144"
//	Mantle               CoinType = "145"
//	ZenEON               CoinType = "146"
//	InternetComputer     CoinType = "147"
//	Tia                  CoinType = "148"
//	MantaPacific         CoinType = "149"
//	NativeZetaChain      CoinType = "150"
//	ZetaEVM              CoinType = "151"
//	Dydx                 CoinType = "152"
//	Merlin               CoinType = "153"
//	Lightlink            CoinType = "154"
//	Blast                CoinType = "155"
//	BounceBit            CoinType = "156"
//	ZkLinkNova           CoinType = "157"
//	Pactus               CoinType = "158"
//	Sonic                CoinType = "159"
//	Polymesh             CoinType = "160"
//)
